
  @URL = https://r1qrdf98db.execute-api.eu-north-1.amazonaws.com

### Get all users
GET {{URL}}/users

### Get user by ID
GET {{URL}}/users/010745c9-d126-438a-b889-e2ebd2b004d2

### Create a new user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "John De",
    "email": "john.d@example.com"
}

### Update user by ID
PUT {{URL}}/users/49e6a687-e233-4588-954a-06af1a5f64b0
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com"
}

### Delete user by ID
DELETE {{URL}}/users/1
