
  @URL = https://r1qrdf98db.execute-api.eu-north-1.amazonaws.com

### Get all users
GET {{URL}}/users

### Get user by ID
GET {{URL}}/users/010745c9-d126-438a-b889-e2ebd2b004d2

### Create a new user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "John",
    "surname": "Doe",
    "email": "john.d@exple.com",
    "password": "password123"
}

### Update user by ID
PUT {{URL}}/users/bd148531-f6dc-497f-ac69-38543b911ce6
Content-Type: application/json

{
    "name": "Janjj Doe",
    "email": "janse.doe@exale.com"
}

### Delete user by ID
DELETE {{URL}}/users/1

### Save a word 
POST {{URL}}/users/bd148531-f6dc-497f-ac69-38543b911ce6/words
Content-Type: application/json

{
    "word": "sin",
    "definition": "a thing characteristic of its kind"
}

### Get all words for a user
GET {{URL}}/users/bd148531-f6dc-497f-ac69-38543b911ce6/words

### Delete a word
DELETE {{URL}}/users/bd148531-f6dc-497f-ac69-38543b911ce6/words
Content-Type: application/json

{
    "word": "sin"
}
